export const MESSAGE_TYPES = Object.freeze({
  CONTENT_SCRIPT_READY: "CONTENT_SCRIPT_READY",
  CONTENT_CONTEXT_PREPARED: "CONTENT_CONTEXT_PREPARED",
  CONTENT_CANDIDATES_UPDATED: "CONTENT_CANDIDATES_UPDATED",
  CONTENT_VIDEO_CANDIDATES_FOUND: "CONTENT_VIDEO_CANDIDATES_FOUND",
  POPUP_GET_STATE: "POPUP_GET_STATE",
  POPUP_FORCE_RESCAN: "POPUP_FORCE_RESCAN",
  POPUP_DOWNLOAD_REQUEST: "POPUP_DOWNLOAD_REQUEST",
  POPUP_DOWNLOAD_VARIANT_REQUEST: "POPUP_DOWNLOAD_VARIANT_REQUEST",
  POPUP_GET_DOWNLOAD_HISTORY: "POPUP_GET_DOWNLOAD_HISTORY",
  POPUP_PING: "POPUP_PING"
});
